sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: gmxOxEdIQVHfFoiPPIb+SDVd16An5EI6IrLcnaxx0r1KcbF+OgPngSA6nnAlhJJyEmWIo78rmNF1NozyUBlytna1e+Oxomnaw3TUi5sckB/gL7/2JAKKDQJxsyHCRnv9V6r+i1PMUJ4AGhxDjKZJ75FJ0zS32pQTTIy/ds6Jak9qEJLRKD2jy2Bnt36FvF7blXrVnzxL0hkojHT6bP5ny2tZgPntxMevBsHCyjuhmGsmvXVDYfG58KQx+4fexpUvqfIMrn+p40uGKJPjhkIt4qDQcEZb+FpkTlwe24u5aktxcOIC/8szPUG5+bQF3o6bRD//D8/XjfWTiy+9DMXz/Uzl+20VVev/i+SG9GO3iCMsiotzP2dKQptg8LYeohtrJrZ61xkU7OjX62fkjjCEeHTN7IdO2mX/XR0oo7M8i3dWtkCLHrYFYEZWFcd743PkazVTFtEnDZdeD0o/+pZxRBci8aEvyvtCrYbpyAHwViKURR+EgGwqTDOA2fy4xwkvdsyz5Y2pf0Wo6rKOyD4Pm+WY34gfzq26vGxrbirHyEyI4KK1jDmvAD86i7lV3yqOnzBxtEevnQApWJPLm6YwEZQKZl1Ld1GacaYQy3U7sSXeVe3pVkSIh82crQ325t/QahUCSSBLT/6hkgOnEotfKaXbFOm8E9acwyOhh+eMvho=
  - secure: Cnd+sAcOlpFa6QhUVMfw6K9wCVnFdkt4dgWpXPGFcASNYQW8i6hcQ5w7F6p4YuAq3qfHgYstOocnp7gLcWnQDRZ66LSJMhv3xdI+nutATR0aw8u4rq/xvM675XWMy3sqfZPE3urSB8POHiFRjYxoZrjFmryzViLMfJixV6LNahi4a/qODHfDgLzEtJ9EcEmOA3yRCIn+l2UBMZYVmx2hp7tHX53T6/nKpVuLtc9yJnbacXhLfFHinljm7Uh0Q9IpShKms9i09ErNASt/bbT5Zxazlhtl5WU0hN5fqtwNJTUA5TAPhx4NhYOlSFtCuntgmABHX7VUJt4dWAXmXwoVgrB/LEBgrFzBGNnxuDbDFYWRWBHb2gkoSGJq8PFK+Dfh17vB9f8Dlpxo8lX1aujf9BdokC3vy3NUupa5m4Wl+j/HW/adOE7OtgZjXa79h11Ge4p9Q8YE3TS1LbWJ/QYsxGKPbFeYmXL5PO8KnZ8iqr68jDp+1V7iILlmpXOAyqd3nC3s9/qO14vQGT9y1Eex04l2JalrPVkLvUwHU7Tj8j2+VcX1EhPxo8dTl+goiaqKHA+KyghY1FlIV0frzs/Ao8q0/ieW2f5rRXEf9/+MsYdeg0eLVw2174TwuZa8Q4BxOLxV1Kygdxw/+vbuTQUsoe7AogbFt3svgzd28+aYwmI=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
