sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: eY+yPbbArvAz6a9lIZSmGwfUgZq6ATaib8tpUQPymcEiC07F82qx+qX8tIJo02Mb1nKGwwIzR5DZUR0lUWyEeLKvuIvLteA18FVl5axv5JuPysIS50uz9PdKkgweju2Rxlt1KrcMul+lMbuwb5ZDvn9zojCjWFGcxnGUrPfxEtqvszI7kqK1tZ9lkHVZPeXAZMbvP3dxHDakQRwOWlRyl4ulWGtSYTW6cNjqQ5I+JVko97xsV/w91Pehr1JF0BGACzXLyQVkEJTjZ6LioQt5uQXVolv1PLhIglWBJAt/xevRGejfAWmuu7/Y0+Wy/uTnFmR2jyTGInwamFM00wJfml5tdAoV6rW2xpb7EW4SLHHsEVt30WsI3uY1KQIUnO2vQmoEZnqF848SQwZSDmB8PEedw79CxFZ1k0G9izMwI5LSKdVxDA56/2gtKksOybY45Q3RMDhqFJaeFluZmaTD7omG+1kAPSYGIx9i362PQXoMsveMd779McwW0XxzkascagSh+BPYHDNVKMuMqQutzYhI+axAqNef34HsT9yPJbJr/Ka6o1wk/uLFxSZCYVoVjQszWMl0s+aydpL3QRhRWhCjinelYXUVkE9VFLKxScyKgRPby0sNOoiecrTFqkELEXs8MPbBf7WNzfrcNtsfpDFDionV8S5fEpbfZbgi2cs=
  - secure: h63FX6xeH7b7xo4HuS1noYXFsF+OZ+wkiC8gwVPQ9Q2MBpvVbreALj2l8yqOt85p64JXgElJgAYHk3XqeP/jic77giGKZkPqEqx/lhwzBnePobHlaUsNbePC6mdJQFnG6VmaPdq1uY+PxoKgJoUM4wNmTqzaqcQsgb7F4ywT1ddE39Nh0u5ksSSTUsvuVm9mxiT8xaUxtaH7d2dHGXuV88sKNJ3MDlVRF7eu7zjoF9S3hFvd18iqIL0SOBaSoTT/87azbdfjiXOBnmxop+lhqCJdt4C0pUofVuNVHQlIDXH07LaG55h0hZEeOsJELInO/Q7Rzq9hLDoMpYj0yU+KBXJJEa4wwH2CFnCCu4kPJvSzLI0UWPHlMX5MAyb7mNpx5oX1vVxTMZcYOg+77eTydFyV6K4eq8oueP5fTpSBVRTaee0Q/ZM0ktL3ReLERoTavv/R/NScJceyev0kpwpaoJPKKuDiAdWO6UaVkZQKJXHo16NZmU3xK7f1J1TCNq2X1AMMqLbhZWMq0Tcgyi5z0O+QQuqMtwiUTq/boShRyn7bcEH52GDpI4OwXdWv9e9TiKF42EoOylFSerx51+WRZv4Xu06eN+R7+NVJ5tGmA16W4mNOOiIklb/k8gooxGmpErRuf2rCYY8ith16N7kyo+A7ZzqKSquyJG502h6YBWc=
